import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createServiceClient } from '@/lib/supabase/service'
import { Resend } from 'resend'
import { z } from 'zod'
import { rateLimit, getClientIp } from '@/lib/ratelimit'

const bodySchema = z.object({
  email: z.string().email(),
})

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://crm.skyglobalsvcs.com'

export async function POST(req: NextRequest) {
  const ip = getClientIp(req)
  if (!rateLimit(`admin-invite:${ip}`, 10, 60_000)) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 })
  }

  try {
    const authClient = await createClient()
    const { data: { user } } = await authClient.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const db = createServiceClient()
    const { data: adminRow } = await db.from('master_admins').select('user_id').eq('user_id', user.id).single()
    if (!adminRow) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

    const body = await req.json()
    const parsed = bodySchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json({ error: 'Valid email required' }, { status: 400 })
    }

    const { email } = parsed.data

    // Create a stub tenant — the invitee becomes owner when they accept.
    // business_name is "Pending Setup" until they fill it in on /signup-like flow.
    const { data: tenant, error: tenantError } = await db
      .from('tenants')
      .insert({
        business_name: 'Pending Setup',
        business_email: email,
        status: 'trial',
        plan: 'beta',
        owner_id: null,
      })
      .select('id')
      .single()

    if (tenantError) {
      return NextResponse.json({ error: tenantError.message }, { status: 500 })
    }

    // Create invite record — token auto-generated by DB default
    const { data: invite, error: inviteError } = await db
      .from('invites')
      .insert({ tenant_id: tenant.id, email, role: 'member' })
      .select('token')
      .single()

    if (inviteError) {
      return NextResponse.json({ error: inviteError.message }, { status: 500 })
    }

    const inviteUrl = `${APP_URL}/invite/${invite.token}`

    if (process.env.RESEND_API_KEY) {
      const resend = new Resend(process.env.RESEND_API_KEY)
      const { PLATFORM } = await import('@/lib/constants')
      await resend.emails.send({
        from: `${PLATFORM.fromName} <${PLATFORM.fromEmail}>`,
        to: [email],
        subject: `You've been invited to ${PLATFORM.shortName}`,
        html: `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f5f0e8;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:520px;margin:0 auto;padding:40px 20px;">
    <div style="text-align:center;margin-bottom:28px;">
      <div style="font-size:28px;font-weight:900;color:#1d1c17;letter-spacing:-0.02em;margin-bottom:4px;">
        Iker's
      </div>
      <div style="font-size:11px;color:#7a6a5a;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;">
        Professional CRM
      </div>
    </div>
    <div style="background:#fffdf7;border:1px solid #e8dcc0;border-radius:14px;padding:36px 32px;box-shadow:0 4px 12px rgba(0,0,0,0.04);">
      <h1 style="font-size:22px;font-weight:800;color:#1d1c17;margin:0 0 12px;letter-spacing:-0.01em;">
        You're invited!
      </h1>
      <p style="font-size:15px;color:#4a3f35;line-height:1.65;margin:0 0 20px;">
        You've been invited to set up an account on <strong>${PLATFORM.fullName}</strong> — the all-in-one platform for managing customers, projects, proposals, invoices, and more.
      </p>
      <div style="background:#faf8f4;border-radius:10px;padding:18px 22px;margin-bottom:28px;">
        <div style="font-size:13px;color:#1d1c17;line-height:2;">
          ✓ Lead tracking &amp; follow-up reminders<br/>
          ✓ Professional proposals with digital signature<br/>
          ✓ Project &amp; expense tracking<br/>
          ✓ Invoice generation<br/>
          ✓ Mobile-friendly — works on your phone
        </div>
      </div>
      <div style="text-align:center;margin-bottom:22px;">
        <a href="${inviteUrl}" style="display:inline-block;padding:14px 32px;background:#e6ab35;color:#1d1c17;text-decoration:none;border-radius:10px;font-weight:800;font-size:15px;letter-spacing:0.02em;">
          Create My Account →
        </a>
      </div>
      <p style="font-size:12px;color:#7a6a5a;text-align:center;margin:0;">
        This invitation expires in 7 days. Link: <a href="${inviteUrl}" style="color:#b8891f;">${inviteUrl}</a>
      </p>
    </div>
    <div style="text-align:center;margin-top:28px;padding-top:16px;border-top:1px solid #e0d5c0;">
      <div style="font-size:11px;color:#7a6a5a;line-height:1.6;">
        ${PLATFORM.fullName}<br/>
        <a href="${PLATFORM.url}" style="color:#b8891f;text-decoration:none;">${PLATFORM.url}</a>
      </div>
    </div>
  </div>
</body>
</html>
        `,
      }).catch(() => {})
    }

    return NextResponse.json({ ok: true, invite_url: inviteUrl }, { status: 201 })
  } catch (err: any) {
    return NextResponse.json({ error: err.message ?? 'Internal error' }, { status: 500 })
  }
}
