import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createServiceClient } from '@/lib/supabase/service'
import { Resend } from 'resend'
import { z } from 'zod'
import { rateLimit, getClientIp } from '@/lib/ratelimit'

const bodySchema = z.object({
  email: z.string().email(),
})

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://crm.skyglobalsvcs.com'

export async function POST(req: NextRequest) {
  const ip = getClientIp(req)
  if (!rateLimit(`admin-invite:${ip}`, 10, 60_000)) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 })
  }

  try {
    const authClient = await createClient()
    const { data: { user } } = await authClient.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const db = createServiceClient()
    const { data: adminRow } = await db.from('master_admins').select('user_id').eq('user_id', user.id).single()
    if (!adminRow) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

    const body = await req.json()
    const parsed = bodySchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json({ error: 'Valid email required' }, { status: 400 })
    }

    const { email } = parsed.data

    // Create a stub tenant — the invitee becomes owner when they accept.
    // business_name is "Pending Setup" until they fill it in on /signup-like flow.
    const { data: tenant, error: tenantError } = await db
      .from('tenants')
      .insert({
        business_name: 'Pending Setup',
        business_email: email,
        status: 'trial',
        plan: 'beta',
        owner_id: null,
      })
      .select('id')
      .single()

    if (tenantError) {
      return NextResponse.json({ error: tenantError.message }, { status: 500 })
    }

    // Create invite record — token auto-generated by DB default
    const { data: invite, error: inviteError } = await db
      .from('invites')
      .insert({ tenant_id: tenant.id, email, role: 'member' })
      .select('token')
      .single()

    if (inviteError) {
      return NextResponse.json({ error: inviteError.message }, { status: 500 })
    }

    const inviteUrl = `${APP_URL}/invite/${invite.token}`

    if (process.env.RESEND_API_KEY) {
      const resend = new Resend(process.env.RESEND_API_KEY)
      await resend.emails.send({
        from: 'SkyGlobal CRM <notifications@skyglobalsvcs.com>',
        to: [email],
        subject: "You've been invited to SkyGlobal CRM",
        html: `
          <div style="font-family: sans-serif; max-width: 520px; margin: 0 auto; color: #1a1a1a;">
            <div style="background: #1d1c17; padding: 24px 32px; border-radius: 8px 8px 0 0;">
              <span style="font-size: 22px; font-weight: 700; color: #e6ab35;">SkyGlobal CRM</span>
            </div>
            <div style="background: #fff; padding: 32px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
              <h2 style="margin: 0 0 12px; color: #1a1a1a;">You're invited</h2>
              <p style="color: #4b5563; margin: 0 0 8px; line-height: 1.6;">
                You've been invited to set up a SkyGlobal CRM account — the all-in-one platform for managing customers, projects, proposals, and more.
              </p>
              <p style="color: #4b5563; margin: 0 0 28px; line-height: 1.6;">
                Click the button below to create your account. This invite expires in <strong>7 days</strong>.
              </p>
              <a href="${inviteUrl}" style="display: inline-block; background: #e6ab35; color: #1d1c17; font-weight: 700; padding: 14px 28px; border-radius: 7px; text-decoration: none; font-size: 15px;">
                Get started →
              </a>
              <p style="color: #9ca3af; font-size: 12px; margin: 24px 0 0;">
                Or copy this link: <a href="${inviteUrl}" style="color: #e6ab35;">${inviteUrl}</a>
              </p>
            </div>
          </div>
        `,
      }).catch(() => {})
    }

    return NextResponse.json({ ok: true, invite_url: inviteUrl }, { status: 201 })
  } catch (err: any) {
    return NextResponse.json({ error: err.message ?? 'Internal error' }, { status: 500 })
  }
}
